apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-signaling-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-signaling-server
  template:
    metadata:
      labels:
        app: my-signaling-server
    spec:
      containers:
        - name: my-signaling-server
          image: webdevregistry-eqg7eebncte8grcz.azurecr.io/my-signaling-server:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8181
      imagePullSecrets:
        - name: acr-secret # We'll create this below if needed