apiVersion: v1
kind: Service
metadata:
  name: my-signaling-server-service
spec:
  type: LoadBalancer
  selector:
    app: my-signaling-server
  ports:
    - protocol: TCP
      port: 443
      targetPort: 8181
