apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-app-poc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-web-app-poc
  template:
    metadata:
      labels:
        app: my-web-app-poc
    spec:
      containers:
        - name: my-web-app-poc
          image: webdevregistry-eqg7eebncte8grcz.azurecr.io/my-web-app-poc:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 443
      imagePullSecrets:
        - name: acr-secret # We'll create this below if needed