apiVersion: v1
kind: Service
metadata:
  name: my-web-app-poc-service
spec:
  type: LoadBalancer
  selector:
    app: my-web-app-poc
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443
